[forest]
trees = ["trees" ]                   # The directories in which your trees are stored
assets = ["assets"]                  # The directories in which your assets are stored
theme = "theme"                      # The directory in which your theme is stored
home = "lc-0001"
base_url = "https://forest.localcharts.org"
host = "localcharts"
